<?php
// Idioma das páginas dinâmicas: ?lang=xx > Accept-Language > pt-BR. Chave = texto em pt-BR.
declare(strict_types=1);

const I18N_LANGS = ['pt-BR' => 'Português', 'en' => 'English', 'es' => 'Español', 'it' => 'Italiano', 'zh' => '中文'];

function lang(): string {
    static $lang = null;
    if ($lang !== null) { return $lang; }
    $q = (string) ($_GET['lang'] ?? $_POST['lang'] ?? '');
    if (isset(I18N_LANGS[$q])) { return $lang = $q; }
    $accept = strtolower((string) ($_SERVER['HTTP_ACCEPT_LANGUAGE'] ?? ''));
    foreach (explode(',', $accept) as $part) {
        $code = trim(explode(';', $part)[0]);
        if ($code === '') { continue; }
        if (str_starts_with($code, 'pt')) { return $lang = 'pt-BR'; }
        if (str_starts_with($code, 'en')) { return $lang = 'en'; }
        if (str_starts_with($code, 'es')) { return $lang = 'es'; }
        if (str_starts_with($code, 'it')) { return $lang = 'it'; }
        if (str_starts_with($code, 'zh')) { return $lang = 'zh'; }
    }
    return $lang = 'pt-BR';
}
function html_lang(): string { return lang() === 'zh' ? 'zh-Hans' : lang(); }
function home_path(): string { return lang() === 'pt-BR' ? '/' : '/' . lang() . '/'; }
function lang_query(): string { return 'lang=' . lang(); }

function lang_switcher(): string {
    $path = strtok((string) ($_SERVER['REQUEST_URI'] ?? '/'), '?');
    $q = $_GET; $out = '';
    foreach (I18N_LANGS as $code => $name) {
        $q['lang'] = $code;
        $flags = ['pt-BR' => '🇧🇷', 'en' => '🇺🇸', 'es' => '🇪🇸', 'it' => '🇮🇹', 'zh' => '🇨🇳'];
        $out .= '<a href="' . htmlspecialchars($path . '?' . http_build_query($q), ENT_QUOTES) . '" class="flag' . ($code === lang() ? ' on' : '') . '" title="' . $name . '" aria-label="' . $name . '">' . $flags[$code] . '</a>';
    }
    return $out;
}

function t(string $key): string {
    $l = lang();
    if ($l === 'pt-BR') { return $key; }
    return I18N[$l][$key] ?? $key;
}

const I18N = [
'en' => [
 'Recursos' => 'Features', 'Acessar por token' => 'Access by token', 'Políticas' => 'Policies', 'Contato' => 'Contact', 'Baixar' => 'Download',
 'Privacidade' => 'Privacy', 'Termos' => 'Terms', 'Uso aceitável' => 'Acceptable use', 'Segurança' => 'Security', 'Denunciar conteúdo' => 'Report content',
 'Esta imagem se autodestrói após a primeira visualização.' => 'This image self-destructs after the first view.', 'visualiz.' => 'views',
 'Copiar link' => 'Copy link', 'Abrir original' => 'Open original', 'Copiado ✓' => 'Copied ✓', 'Copie o link:' => 'Copy the link:',
 'Esta imagem já foi visualizada e se autodestruiu.' => 'This image has already been viewed and self-destructed.',
 'Ela foi compartilhada no modo “ver apenas uma vez”: depois da primeira exibição, o arquivo é apagado do servidor.' => 'It was shared in “view once” mode: after the first display, the file is deleted from the server.',
 'Este link não está mais disponível' => 'This link is no longer available',
 'Ele expirou ou foi revogado por quem o criou. Links do SnapLens têm validade definida na hora do compartilhamento.' => 'It expired or was revoked by its creator. SnapLens links have an expiry set at share time.',
 'Conheça o SnapLens' => 'Meet SnapLens', 'Compartilhado com' => 'Shared with', 'para macOS' => 'for macOS', 'Link indisponível' => 'Link unavailable', 'Screenshot' => 'Screenshot',
 'não expira' => 'never expires', 'expirado' => 'expired', 'expira em %d min' => 'expires in %d min', 'expira em %d h' => 'expires in %d h', 'expira em %d dias' => 'expires in %d days',
 'Muitas tentativas seguidas. Tente novamente em alguns minutos.' => 'Too many attempts in a row. Try again in a few minutes.',
 'Token não encontrado ou link já removido.' => 'Token not found or link already removed.', 'Marque a confirmação para apagar a imagem.' => 'Tick the confirmation to delete the image.',
 'Cole o token de exclusão gerado pelo app para localizar ou apagar sua imagem.' => 'Paste the delete token generated by the app to find or delete your image.',
 'Imagem encontrada' => 'Image found', 'Link' => 'Link', 'Criado' => 'Created', 'Validade' => 'Expiry', 'Visualizações' => 'Views', 'Tamanho' => 'Size', 'Ver apenas uma vez' => 'View once',
 'Confirmo que quero apagar esta imagem do servidor.' => 'I confirm I want to delete this image from the server.', 'Apagar imagem' => 'Delete image', 'Token de exclusão' => 'Delete token', 'Localizar imagem' => 'Find image',
 'Imagem apagada do servidor.' => 'Image deleted from the server.', 'sim' => 'yes', 'não' => 'no',
 'Nome muito longo (máx. 100 caracteres).' => 'Name too long (max. 100 characters).', 'Informe um e-mail válido.' => 'Enter a valid e-mail.', 'Escreva sua mensagem.' => 'Write your message.',
 'Mensagem muito longa (máx. 5000 caracteres).' => 'Message too long (max. 5000 characters).', 'Muitas mensagens seguidas. Tente novamente em alguns minutos.' => 'Too many messages in a row. Try again in a few minutes.',
 'Não foi possível enviar agora. Tente de novo em alguns minutos ou escreva para ' => 'Could not send right now. Try again in a few minutes or write to ',
 'Mensagem enviada! Respondemos no e-mail informado.' => 'Message sent! We reply to the e-mail you provided.', 'Voltar ao início' => 'Back to home',
 'Dúvidas, sugestões ou denúncias: preencha abaixo ou escreva para ' => 'Questions, suggestions or reports: fill in below or write to ',
 'Nome' => 'Name', '(opcional)' => '(optional)', 'E-mail' => 'E-mail', 'Assunto' => 'Subject', 'Cole o link que quer denunciar na mensagem.' => 'Paste the link you want to report in the message.',
 'Mensagem' => 'Message', 'Enviar mensagem' => 'Send message', 'Dúvida ou sugestão' => 'Question or suggestion', 'Denunciar link/imagem' => 'Report link/image', 'Solicitação de dados (LGPD)' => 'Data request (LGPD)', 'Segurança (vulnerabilidade)' => 'Security (vulnerability)', 'Outro' => 'Other',
],
'es' => [
 'Recursos' => 'Funciones', 'Acessar por token' => 'Acceder por token', 'Políticas' => 'Políticas', 'Contato' => 'Contacto', 'Baixar' => 'Descargar',
 'Privacidade' => 'Privacidad', 'Termos' => 'Términos', 'Uso aceitável' => 'Uso aceptable', 'Segurança' => 'Seguridad', 'Denunciar conteúdo' => 'Denunciar contenido',
 'Esta imagem se autodestrói após a primeira visualização.' => 'Esta imagen se autodestruye tras la primera visualización.', 'visualiz.' => 'vistas',
 'Copiar link' => 'Copiar enlace', 'Abrir original' => 'Abrir original', 'Copiado ✓' => 'Copiado ✓', 'Copie o link:' => 'Copia el enlace:',
 'Esta imagem já foi visualizada e se autodestruiu.' => 'Esta imagen ya fue vista y se autodestruyó.',
 'Ela foi compartilhada no modo “ver apenas uma vez”: depois da primeira exibição, o arquivo é apagado do servidor.' => 'Se compartió en modo “ver solo una vez”: tras la primera visualización, el archivo se borra del servidor.',
 'Este link não está mais disponível' => 'Este enlace ya no está disponible',
 'Ele expirou ou foi revogado por quem o criou. Links do SnapLens têm validade definida na hora do compartilhamento.' => 'Caducó o fue revocado por quien lo creó. Los enlaces de SnapLens tienen una validez definida al compartir.',
 'Conheça o SnapLens' => 'Conoce SnapLens', 'Compartilhado com' => 'Compartido con', 'para macOS' => 'para macOS', 'Link indisponível' => 'Enlace no disponible', 'Screenshot' => 'Captura',
 'não expira' => 'no caduca', 'expirado' => 'caducado', 'expira em %d min' => 'caduca en %d min', 'expira em %d h' => 'caduca en %d h', 'expira em %d dias' => 'caduca en %d días',
 'Muitas tentativas seguidas. Tente novamente em alguns minutos.' => 'Demasiados intentos seguidos. Inténtalo de nuevo en unos minutos.',
 'Token não encontrado ou link já removido.' => 'Token no encontrado o enlace ya eliminado.', 'Marque a confirmação para apagar a imagem.' => 'Marca la confirmación para borrar la imagen.',
 'Cole o token de exclusão gerado pelo app para localizar ou apagar sua imagem.' => 'Pega el token de eliminación generado por la app para localizar o borrar tu imagen.',
 'Imagem encontrada' => 'Imagen encontrada', 'Link' => 'Enlace', 'Criado' => 'Creado', 'Validade' => 'Validez', 'Visualizações' => 'Visualizaciones', 'Tamanho' => 'Tamaño', 'Ver apenas uma vez' => 'Ver solo una vez',
 'Confirmo que quero apagar esta imagem do servidor.' => 'Confirmo que quiero borrar esta imagen del servidor.', 'Apagar imagem' => 'Borrar imagen', 'Token de exclusão' => 'Token de eliminación', 'Localizar imagem' => 'Localizar imagen',
 'Imagem apagada do servidor.' => 'Imagen borrada del servidor.', 'sim' => 'sí', 'não' => 'no',
 'Nome muito longo (máx. 100 caracteres).' => 'Nombre demasiado largo (máx. 100 caracteres).', 'Informe um e-mail válido.' => 'Indica un e-mail válido.', 'Escreva sua mensagem.' => 'Escribe tu mensaje.',
 'Mensagem muito longa (máx. 5000 caracteres).' => 'Mensaje demasiado largo (máx. 5000 caracteres).', 'Muitas mensagens seguidas. Tente novamente em alguns minutos.' => 'Demasiados mensajes seguidos. Inténtalo de nuevo en unos minutos.',
 'Não foi possível enviar agora. Tente de novo em alguns minutos ou escreva para ' => 'No se pudo enviar ahora. Inténtalo de nuevo en unos minutos o escribe a ',
 'Mensagem enviada! Respondemos no e-mail informado.' => '¡Mensaje enviado! Respondemos al e-mail indicado.', 'Voltar ao início' => 'Volver al inicio',
 'Dúvidas, sugestões ou denúncias: preencha abaixo ou escreva para ' => 'Dudas, sugerencias o denuncias: rellena abajo o escribe a ',
 'Nome' => 'Nombre', '(opcional)' => '(opcional)', 'E-mail' => 'E-mail', 'Assunto' => 'Asunto', 'Cole o link que quer denunciar na mensagem.' => 'Pega en el mensaje el enlace que quieres denunciar.',
 'Mensagem' => 'Mensaje', 'Enviar mensagem' => 'Enviar mensaje', 'Dúvida ou sugestão' => 'Duda o sugerencia', 'Denunciar link/imagem' => 'Denunciar enlace/imagen', 'Solicitação de dados (LGPD)' => 'Solicitud de datos (LGPD)', 'Segurança (vulnerabilidade)' => 'Seguridad (vulnerabilidad)', 'Outro' => 'Otro',
],
'it' => [
 'Recursos' => 'Funzioni', 'Acessar por token' => 'Accedi con il token', 'Políticas' => 'Politiche', 'Contato' => 'Contatti', 'Baixar' => 'Scarica',
 'Privacidade' => 'Privacy', 'Termos' => 'Termini', 'Uso aceitável' => 'Uso accettabile', 'Segurança' => 'Sicurezza', 'Denunciar conteúdo' => 'Segnala contenuto',
 'Esta imagem se autodestrói após a primeira visualização.' => 'Questa immagine si autodistrugge dopo la prima visualizzazione.', 'visualiz.' => 'visualizz.',
 'Copiar link' => 'Copia link', 'Abrir original' => 'Apri originale', 'Copiado ✓' => 'Copiato ✓', 'Copie o link:' => 'Copia il link:',
 'Esta imagem já foi visualizada e se autodestruiu.' => 'Questa immagine è già stata vista e si è autodistrutta.',
 'Ela foi compartilhada no modo “ver apenas uma vez”: depois da primeira exibição, o arquivo é apagado do servidor.' => 'È stata condivisa in modalità “visualizzazione singola”: dopo la prima apertura il file viene eliminato dal server.',
 'Este link não está mais disponível' => 'Questo link non è più disponibile',
 'Ele expirou ou foi revogado por quem o criou. Links do SnapLens têm validade definida na hora do compartilhamento.' => 'È scaduto o è stato revocato da chi lo ha creato. I link di SnapLens hanno una scadenza definita al momento della condivisione.',
 'Conheça o SnapLens' => 'Scopri SnapLens', 'Compartilhado com' => 'Condiviso con', 'para macOS' => 'per macOS', 'Link indisponível' => 'Link non disponibile', 'Screenshot' => 'Screenshot',
 'não expira' => 'non scade', 'expirado' => 'scaduto', 'expira em %d min' => 'scade tra %d min', 'expira em %d h' => 'scade tra %d h', 'expira em %d dias' => 'scade tra %d giorni',
 'Muitas tentativas seguidas. Tente novamente em alguns minutos.' => 'Troppi tentativi di seguito. Riprova tra qualche minuto.',
 'Token não encontrado ou link já removido.' => 'Token non trovato o link già rimosso.', 'Marque a confirmação para apagar a imagem.' => 'Spunta la conferma per eliminare l\'immagine.',
 'Cole o token de exclusão gerado pelo app para localizar ou apagar sua imagem.' => 'Incolla il token di eliminazione generato dall\'app per trovare o eliminare la tua immagine.',
 'Imagem encontrada' => 'Immagine trovata', 'Link' => 'Link', 'Criado' => 'Creato', 'Validade' => 'Scadenza', 'Visualizações' => 'Visualizzazioni', 'Tamanho' => 'Dimensione', 'Ver apenas uma vez' => 'Visualizzazione singola',
 'Confirmo que quero apagar esta imagem do servidor.' => 'Confermo di voler eliminare questa immagine dal server.', 'Apagar imagem' => 'Elimina immagine', 'Token de exclusão' => 'Token di eliminazione', 'Localizar imagem' => 'Trova immagine',
 'Imagem apagada do servidor.' => 'Immagine eliminata dal server.', 'sim' => 'sì', 'não' => 'no',
 'Nome muito longo (máx. 100 caracteres).' => 'Nome troppo lungo (max 100 caratteri).', 'Informe um e-mail válido.' => 'Inserisci un\'e-mail valida.', 'Escreva sua mensagem.' => 'Scrivi il tuo messaggio.',
 'Mensagem muito longa (máx. 5000 caracteres).' => 'Messaggio troppo lungo (max 5000 caratteri).', 'Muitas mensagens seguidas. Tente novamente em alguns minutos.' => 'Troppi messaggi di seguito. Riprova tra qualche minuto.',
 'Não foi possível enviar agora. Tente de novo em alguns minutos ou escreva para ' => 'Invio non riuscito. Riprova tra qualche minuto o scrivi a ',
 'Mensagem enviada! Respondemos no e-mail informado.' => 'Messaggio inviato! Rispondiamo all\'e-mail indicata.', 'Voltar ao início' => 'Torna alla home',
 'Dúvidas, sugestões ou denúncias: preencha abaixo ou escreva para ' => 'Domande, suggerimenti o segnalazioni: compila qui sotto o scrivi a ',
 'Nome' => 'Nome', '(opcional)' => '(facoltativo)', 'E-mail' => 'E-mail', 'Assunto' => 'Oggetto', 'Cole o link que quer denunciar na mensagem.' => 'Incolla nel messaggio il link che vuoi segnalare.',
 'Mensagem' => 'Messaggio', 'Enviar mensagem' => 'Invia messaggio', 'Dúvida ou sugestão' => 'Domanda o suggerimento', 'Denunciar link/imagem' => 'Segnala link/immagine', 'Solicitação de dados (LGPD)' => 'Richiesta dati (LGPD)', 'Segurança (vulnerabilidade)' => 'Sicurezza (vulnerabilità)', 'Outro' => 'Altro',
],
'zh' => [
 'Recursos' => '功能', 'Acessar por token' => '通过令牌访问', 'Políticas' => '政策', 'Contato' => '联系', 'Baixar' => '下载',
 'Privacidade' => '隐私', 'Termos' => '条款', 'Uso aceitável' => '可接受使用', 'Segurança' => '安全', 'Denunciar conteúdo' => '举报内容',
 'Esta imagem se autodestrói após a primeira visualização.' => '此图片在首次查看后将自动销毁。', 'visualiz.' => '次查看',
 'Copiar link' => '复制链接', 'Abrir original' => '打开原图', 'Copiado ✓' => '已复制 ✓', 'Copie o link:' => '请复制链接：',
 'Esta imagem já foi visualizada e se autodestruiu.' => '此图片已被查看并已自毁。',
 'Ela foi compartilhada no modo “ver apenas uma vez”: depois da primeira exibição, o arquivo é apagado do servidor.' => '它以“阅后即焚”模式分享：首次显示后，文件即从服务器删除。',
 'Este link não está mais disponível' => '此链接已不可用',
 'Ele expirou ou foi revogado por quem o criou. Links do SnapLens têm validade definida na hora do compartilhamento.' => '它已过期或被创建者撤销。SnapLens 链接的有效期在分享时设定。',
 'Conheça o SnapLens' => '了解 SnapLens', 'Compartilhado com' => '分享自', 'para macOS' => 'macOS 版', 'Link indisponível' => '链接不可用', 'Screenshot' => '截图',
 'não expira' => '永不过期', 'expirado' => '已过期', 'expira em %d min' => '%d 分钟后过期', 'expira em %d h' => '%d 小时后过期', 'expira em %d dias' => '%d 天后过期',
 'Muitas tentativas seguidas. Tente novamente em alguns minutos.' => '尝试次数过多，请几分钟后重试。',
 'Token não encontrado ou link já removido.' => '未找到令牌，或链接已删除。', 'Marque a confirmação para apagar a imagem.' => '请勾选确认以删除图片。',
 'Cole o token de exclusão gerado pelo app para localizar ou apagar sua imagem.' => '粘贴应用生成的删除令牌，以查找或删除你的图片。',
 'Imagem encontrada' => '已找到图片', 'Link' => '链接', 'Criado' => '创建时间', 'Validade' => '有效期', 'Visualizações' => '查看次数', 'Tamanho' => '大小', 'Ver apenas uma vez' => '阅后即焚',
 'Confirmo que quero apagar esta imagem do servidor.' => '我确认要从服务器删除此图片。', 'Apagar imagem' => '删除图片', 'Token de exclusão' => '删除令牌', 'Localizar imagem' => '查找图片',
 'Imagem apagada do servidor.' => '图片已从服务器删除。', 'sim' => '是', 'não' => '否',
 'Nome muito longo (máx. 100 caracteres).' => '姓名过长（最多 100 个字符）。', 'Informe um e-mail válido.' => '请输入有效的电子邮件。', 'Escreva sua mensagem.' => '请填写留言。',
 'Mensagem muito longa (máx. 5000 caracteres).' => '留言过长（最多 5000 个字符）。', 'Muitas mensagens seguidas. Tente novamente em alguns minutos.' => '发送过于频繁，请几分钟后重试。',
 'Não foi possível enviar agora. Tente de novo em alguns minutos ou escreva para ' => '目前无法发送。请几分钟后重试，或发送邮件至 ',
 'Mensagem enviada! Respondemos no e-mail informado.' => '留言已发送！我们会回复到你提供的邮箱。', 'Voltar ao início' => '返回首页',
 'Dúvidas, sugestões ou denúncias: preencha abaixo ou escreva para ' => '疑问、建议或举报：请填写下方表单，或发送邮件至 ',
 'Nome' => '姓名', '(opcional)' => '（可选）', 'E-mail' => '电子邮件', 'Assunto' => '主题', 'Cole o link que quer denunciar na mensagem.' => '请在留言中粘贴要举报的链接。',
 'Mensagem' => '留言', 'Enviar mensagem' => '发送留言', 'Dúvida ou sugestão' => '疑问或建议', 'Denunciar link/imagem' => '举报链接/图片', 'Solicitação de dados (LGPD)' => '数据请求（LGPD）', 'Segurança (vulnerabilidade)' => '安全（漏洞）', 'Outro' => '其他',
],
];
